
screen_width = 960
screen_hight = 640

function init(self)
	self.clicks = 0	
	self.ten_items = {}
end

function on_message(self, message_id, message, sender)
	if message_id == hash("addPoint") then
		onAddPoint(self)
	end
end

function onAddPoint(self)
	self.clicks = self.clicks + 1
	msg.post("canvas#canvas", "addPoint", { string = tostring(self.clicks), int = self.clicks})
	
	local mod = self.clicks % 10
	if mod == 0 then
		table.insert(self.ten_items, factory.create("#ten"))
	end

end

	