local total_pie = 360
local portion = 10
local pie_portion = total_pie / portion

function init(self)
	self.txt_clickCount = gui.get_node("txt_clickCount")
	self.pie_nextSpawn = gui.get_node("pie_nextSpawn")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("addPoint") then
		gui.set_text(self.txt_clickCount, message.string)
		gui.set_fill_angle(self.pie_nextSpawn, total_pie - (message.int % portion) * pie_portion)
	end
end