
function init(self)
	msg.post(".", "acquire_input_focus")
	self.radius = go.get("#sprite", hash("size")).x / 2
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		local point = vmath.vector3(action.x, action.y, 1)
		local position = go.get_position()
		if vmath.length(point - position) < self.radius then
			msg.post("gameManager#gameManager", "addPoint")
		end
	end
end
